# Generated by Django 5.1.1 on 2024-10-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('products', models.JSONField(default=dict)),
                ('description', models.CharField(max_length=1000000000)),
                ('registred_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
