# Generated by Django 5.1.1 on 2024-10-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_registred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registred_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
