# Generated by Django 5.1.1 on 2024-10-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_registred_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
