# Generated by Django 5.1.1 on 2024-10-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
