# Generated by Django 5.1.1 on 2024-10-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
